version: "3.8"

services:
  # ----------------------------
  # PostgreSQL Database
  # ----------------------------
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantacy_manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # ----------------------------
  # Redis
  # ----------------------------
  redis:
    image: redis:7
    container_name: redis
    environment:
      REDIS_PASSWORD: "password"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ----------------------------
  # Backend
  # ----------------------------
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      PORT: 5000

      # Database Vars
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: fantacy_manager

      # Redis Vars
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # JWT secret
      JWT_SECRET: kareem-secret

      # FRONTEND
      FRONTEND_URL: "http://localhost:5173"

volumes:
  db_data:
  redis_data:
